// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CrawlerServiceClient is the client API for CrawlerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrawlerServiceClient interface {
	CreateCrawler(ctx context.Context, in *CrawlerMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListCrawler(ctx context.Context, in *SourceIdMessage, opts ...grpc.CallOption) (*CrawlerMessage, error)
	StartCrawler(ctx context.Context, in *SourceIdMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StopCrawler(ctx context.Context, in *SourceIdMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type crawlerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrawlerServiceClient(cc grpc.ClientConnInterface) CrawlerServiceClient {
	return &crawlerServiceClient{cc}
}

func (c *crawlerServiceClient) CreateCrawler(ctx context.Context, in *CrawlerMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tickerscraper.v1.CrawlerService/CreateCrawler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) ListCrawler(ctx context.Context, in *SourceIdMessage, opts ...grpc.CallOption) (*CrawlerMessage, error) {
	out := new(CrawlerMessage)
	err := c.cc.Invoke(ctx, "/tickerscraper.v1.CrawlerService/ListCrawler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) StartCrawler(ctx context.Context, in *SourceIdMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tickerscraper.v1.CrawlerService/StartCrawler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) StopCrawler(ctx context.Context, in *SourceIdMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tickerscraper.v1.CrawlerService/StopCrawler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawlerServiceServer is the server API for CrawlerService service.
// All implementations must embed UnimplementedCrawlerServiceServer
// for forward compatibility
type CrawlerServiceServer interface {
	CreateCrawler(context.Context, *CrawlerMessage) (*emptypb.Empty, error)
	ListCrawler(context.Context, *SourceIdMessage) (*CrawlerMessage, error)
	StartCrawler(context.Context, *SourceIdMessage) (*emptypb.Empty, error)
	StopCrawler(context.Context, *SourceIdMessage) (*emptypb.Empty, error)
	mustEmbedUnimplementedCrawlerServiceServer()
}

// UnimplementedCrawlerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCrawlerServiceServer struct {
}

func (UnimplementedCrawlerServiceServer) CreateCrawler(context.Context, *CrawlerMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCrawler not implemented")
}
func (UnimplementedCrawlerServiceServer) ListCrawler(context.Context, *SourceIdMessage) (*CrawlerMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCrawler not implemented")
}
func (UnimplementedCrawlerServiceServer) StartCrawler(context.Context, *SourceIdMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCrawler not implemented")
}
func (UnimplementedCrawlerServiceServer) StopCrawler(context.Context, *SourceIdMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopCrawler not implemented")
}
func (UnimplementedCrawlerServiceServer) mustEmbedUnimplementedCrawlerServiceServer() {}

// UnsafeCrawlerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrawlerServiceServer will
// result in compilation errors.
type UnsafeCrawlerServiceServer interface {
	mustEmbedUnimplementedCrawlerServiceServer()
}

func RegisterCrawlerServiceServer(s grpc.ServiceRegistrar, srv CrawlerServiceServer) {
	s.RegisterService(&CrawlerService_ServiceDesc, srv)
}

func _CrawlerService_CreateCrawler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlerMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).CreateCrawler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tickerscraper.v1.CrawlerService/CreateCrawler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).CreateCrawler(ctx, req.(*CrawlerMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_ListCrawler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceIdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).ListCrawler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tickerscraper.v1.CrawlerService/ListCrawler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).ListCrawler(ctx, req.(*SourceIdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_StartCrawler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceIdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).StartCrawler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tickerscraper.v1.CrawlerService/StartCrawler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).StartCrawler(ctx, req.(*SourceIdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_StopCrawler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceIdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).StopCrawler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tickerscraper.v1.CrawlerService/StopCrawler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).StopCrawler(ctx, req.(*SourceIdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// CrawlerService_ServiceDesc is the grpc.ServiceDesc for CrawlerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrawlerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tickerscraper.v1.CrawlerService",
	HandlerType: (*CrawlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCrawler",
			Handler:    _CrawlerService_CreateCrawler_Handler,
		},
		{
			MethodName: "ListCrawler",
			Handler:    _CrawlerService_ListCrawler_Handler,
		},
		{
			MethodName: "StartCrawler",
			Handler:    _CrawlerService_StartCrawler_Handler,
		},
		{
			MethodName: "StopCrawler",
			Handler:    _CrawlerService_StopCrawler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
