// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: enqueuer.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Action    int32  `protobuf:"varint,2,opt,name=Action,proto3" json:"Action,omitempty"`
	Selector  string `protobuf:"bytes,3,opt,name=Selector,proto3" json:"Selector,omitempty"`
	Attribute string `protobuf:"bytes,4,opt,name=Attribute,proto3" json:"Attribute,omitempty"`
}

func (x *Rule) Reset() {
	*x = Rule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enqueuer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_enqueuer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_enqueuer_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *Rule) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *Rule) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

type AllowedDomain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain            string `protobuf:"bytes,1,opt,name=Domain,proto3" json:"Domain,omitempty"`
	URLRegexValidator int32  `protobuf:"varint,2,opt,name=URLRegexValidator,proto3" json:"URLRegexValidator,omitempty"`
}

func (x *AllowedDomain) Reset() {
	*x = AllowedDomain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enqueuer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowedDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowedDomain) ProtoMessage() {}

func (x *AllowedDomain) ProtoReflect() protoreflect.Message {
	mi := &file_enqueuer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowedDomain.ProtoReflect.Descriptor instead.
func (*AllowedDomain) Descriptor() ([]byte, []int) {
	return file_enqueuer_proto_rawDescGZIP(), []int{1}
}

func (x *AllowedDomain) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AllowedDomain) GetURLRegexValidator() int32 {
	if x != nil {
		return x.URLRegexValidator
	}
	return 0
}

// Deal: A deal is the reflection of the fact of a trade operation execution based on an order that contains a trade request
type Enqueuer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnqueuerID        string           `protobuf:"bytes,1,opt,name=EnqueuerID,proto3" json:"EnqueuerID,omitempty"`
	SourceID          int32            `protobuf:"varint,2,opt,name=SourceID,proto3" json:"SourceID,omitempty"`
	StartURL          string           `protobuf:"bytes,3,opt,name=StartURL,proto3" json:"StartURL,omitempty"`
	AllowedDomain     []*AllowedDomain `protobuf:"bytes,4,rep,name=AllowedDomain,proto3" json:"AllowedDomain,omitempty"`
	DurationInMinutes uint32           `protobuf:"varint,5,opt,name=DurationInMinutes,proto3" json:"DurationInMinutes,omitempty"`
	MaxDepth          uint32           `protobuf:"varint,6,opt,name=MaxDepth,proto3" json:"MaxDepth,omitempty"`
	Aborted           bool             `protobuf:"varint,7,opt,name=Aborted,proto3" json:"Aborted,omitempty"`
	Rules             []*Rule          `protobuf:"bytes,8,rep,name=Rules,proto3" json:"Rules,omitempty"`
}

func (x *Enqueuer) Reset() {
	*x = Enqueuer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enqueuer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Enqueuer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enqueuer) ProtoMessage() {}

func (x *Enqueuer) ProtoReflect() protoreflect.Message {
	mi := &file_enqueuer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enqueuer.ProtoReflect.Descriptor instead.
func (*Enqueuer) Descriptor() ([]byte, []int) {
	return file_enqueuer_proto_rawDescGZIP(), []int{2}
}

func (x *Enqueuer) GetEnqueuerID() string {
	if x != nil {
		return x.EnqueuerID
	}
	return ""
}

func (x *Enqueuer) GetSourceID() int32 {
	if x != nil {
		return x.SourceID
	}
	return 0
}

func (x *Enqueuer) GetStartURL() string {
	if x != nil {
		return x.StartURL
	}
	return ""
}

func (x *Enqueuer) GetAllowedDomain() []*AllowedDomain {
	if x != nil {
		return x.AllowedDomain
	}
	return nil
}

func (x *Enqueuer) GetDurationInMinutes() uint32 {
	if x != nil {
		return x.DurationInMinutes
	}
	return 0
}

func (x *Enqueuer) GetMaxDepth() uint32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *Enqueuer) GetAborted() bool {
	if x != nil {
		return x.Aborted
	}
	return false
}

func (x *Enqueuer) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

var File_enqueuer_proto protoreflect.FileDescriptor

var file_enqueuer_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x22, 0x6c, 0x0a, 0x04, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x22, 0x55, 0x0a, 0x0d, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x2c, 0x0a, 0x11, 0x55, 0x52, 0x4c,
	0x52, 0x65, 0x67, 0x65, 0x78, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x67, 0x65, 0x78, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xbb, 0x02, 0x0a, 0x08, 0x45, 0x6e, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x45, 0x0a, 0x0d,
	0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x63, 0x72, 0x61,
	0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x44, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x52, 0x0d, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x44, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x12, 0x2c, 0x0a, 0x11, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x61, 0x78, 0x44, 0x65, 0x70, 0x74, 0x68, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x4d, 0x61, 0x78, 0x44, 0x65, 0x70, 0x74, 0x68, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x41, 0x62, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x05, 0x52, 0x75, 0x6c, 0x65, 0x73,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x73,
	0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05,
	0x52, 0x75, 0x6c, 0x65, 0x73, 0x42, 0x13, 0x5a, 0x11, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x2d,
	0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_enqueuer_proto_rawDescOnce sync.Once
	file_enqueuer_proto_rawDescData = file_enqueuer_proto_rawDesc
)

func file_enqueuer_proto_rawDescGZIP() []byte {
	file_enqueuer_proto_rawDescOnce.Do(func() {
		file_enqueuer_proto_rawDescData = protoimpl.X.CompressGZIP(file_enqueuer_proto_rawDescData)
	})
	return file_enqueuer_proto_rawDescData
}

var file_enqueuer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_enqueuer_proto_goTypes = []interface{}{
	(*Rule)(nil),          // 0: tickerscraper.v1.Rule
	(*AllowedDomain)(nil), // 1: tickerscraper.v1.AllowedDomain
	(*Enqueuer)(nil),      // 2: tickerscraper.v1.Enqueuer
}
var file_enqueuer_proto_depIdxs = []int32{
	1, // 0: tickerscraper.v1.Enqueuer.AllowedDomain:type_name -> tickerscraper.v1.AllowedDomain
	0, // 1: tickerscraper.v1.Enqueuer.Rules:type_name -> tickerscraper.v1.Rule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_enqueuer_proto_init() }
func file_enqueuer_proto_init() {
	if File_enqueuer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_enqueuer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enqueuer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowedDomain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enqueuer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Enqueuer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enqueuer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enqueuer_proto_goTypes,
		DependencyIndexes: file_enqueuer_proto_depIdxs,
		MessageInfos:      file_enqueuer_proto_msgTypes,
	}.Build()
	File_enqueuer_proto = out.File
	file_enqueuer_proto_rawDesc = nil
	file_enqueuer_proto_goTypes = nil
	file_enqueuer_proto_depIdxs = nil
}
