// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package mql5_background_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RuscignoMetatrader5ServiceClient is the client API for RuscignoMetatrader5Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuscignoMetatrader5ServiceClient interface {
	// Create a new account
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Create new deals
	CreateDeals(ctx context.Context, in *CreateDealsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Create new orders
	CreateOrders(ctx context.Context, in *CreateOrdersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Create new positions
	CreatePositions(ctx context.Context, in *CreatePositionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type ruscignoMetatrader5ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuscignoMetatrader5ServiceClient(cc grpc.ClientConnInterface) RuscignoMetatrader5ServiceClient {
	return &ruscignoMetatrader5ServiceClient{cc}
}

func (c *ruscignoMetatrader5ServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/mql5_background.v1.RuscignoMetatrader5Service/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruscignoMetatrader5ServiceClient) CreateDeals(ctx context.Context, in *CreateDealsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/mql5_background.v1.RuscignoMetatrader5Service/CreateDeals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruscignoMetatrader5ServiceClient) CreateOrders(ctx context.Context, in *CreateOrdersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/mql5_background.v1.RuscignoMetatrader5Service/CreateOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruscignoMetatrader5ServiceClient) CreatePositions(ctx context.Context, in *CreatePositionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/mql5_background.v1.RuscignoMetatrader5Service/CreatePositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuscignoMetatrader5ServiceServer is the server API for RuscignoMetatrader5Service service.
// All implementations must embed UnimplementedRuscignoMetatrader5ServiceServer
// for forward compatibility
type RuscignoMetatrader5ServiceServer interface {
	// Create a new account
	CreateAccount(context.Context, *CreateAccountRequest) (*emptypb.Empty, error)
	// Create new deals
	CreateDeals(context.Context, *CreateDealsRequest) (*emptypb.Empty, error)
	// Create new orders
	CreateOrders(context.Context, *CreateOrdersRequest) (*emptypb.Empty, error)
	// Create new positions
	CreatePositions(context.Context, *CreatePositionsRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedRuscignoMetatrader5ServiceServer()
}

// UnimplementedRuscignoMetatrader5ServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRuscignoMetatrader5ServiceServer struct {
}

func (UnimplementedRuscignoMetatrader5ServiceServer) CreateAccount(context.Context, *CreateAccountRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedRuscignoMetatrader5ServiceServer) CreateDeals(context.Context, *CreateDealsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeals not implemented")
}
func (UnimplementedRuscignoMetatrader5ServiceServer) CreateOrders(context.Context, *CreateOrdersRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrders not implemented")
}
func (UnimplementedRuscignoMetatrader5ServiceServer) CreatePositions(context.Context, *CreatePositionsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePositions not implemented")
}
func (UnimplementedRuscignoMetatrader5ServiceServer) mustEmbedUnimplementedRuscignoMetatrader5ServiceServer() {
}

// UnsafeRuscignoMetatrader5ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuscignoMetatrader5ServiceServer will
// result in compilation errors.
type UnsafeRuscignoMetatrader5ServiceServer interface {
	mustEmbedUnimplementedRuscignoMetatrader5ServiceServer()
}

func RegisterRuscignoMetatrader5ServiceServer(s grpc.ServiceRegistrar, srv RuscignoMetatrader5ServiceServer) {
	s.RegisterService(&RuscignoMetatrader5Service_ServiceDesc, srv)
}

func _RuscignoMetatrader5Service_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuscignoMetatrader5ServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mql5_background.v1.RuscignoMetatrader5Service/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuscignoMetatrader5ServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuscignoMetatrader5Service_CreateDeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuscignoMetatrader5ServiceServer).CreateDeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mql5_background.v1.RuscignoMetatrader5Service/CreateDeals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuscignoMetatrader5ServiceServer).CreateDeals(ctx, req.(*CreateDealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuscignoMetatrader5Service_CreateOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuscignoMetatrader5ServiceServer).CreateOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mql5_background.v1.RuscignoMetatrader5Service/CreateOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuscignoMetatrader5ServiceServer).CreateOrders(ctx, req.(*CreateOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuscignoMetatrader5Service_CreatePositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuscignoMetatrader5ServiceServer).CreatePositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mql5_background.v1.RuscignoMetatrader5Service/CreatePositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuscignoMetatrader5ServiceServer).CreatePositions(ctx, req.(*CreatePositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuscignoMetatrader5Service_ServiceDesc is the grpc.ServiceDesc for RuscignoMetatrader5Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuscignoMetatrader5Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mql5_background.v1.RuscignoMetatrader5Service",
	HandlerType: (*RuscignoMetatrader5ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _RuscignoMetatrader5Service_CreateAccount_Handler,
		},
		{
			MethodName: "CreateDeals",
			Handler:    _RuscignoMetatrader5Service_CreateDeals_Handler,
		},
		{
			MethodName: "CreateOrders",
			Handler:    _RuscignoMetatrader5Service_CreateOrders_Handler,
		},
		{
			MethodName: "CreatePositions",
			Handler:    _RuscignoMetatrader5Service_CreatePositions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
